FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /super-client ./cmd/super-client

FROM alpine:3.21
RUN apk --no-cache add ca-certificates
COPY --from=builder /super-client /super-client
CMD ["/super-client"]
